language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install ipython
  - pip install nbconvert
  - pip install matplotlib
  - pip install pytest-cov
  - pip install codecov
# command to run tests
script:
  - pytest --cov=./ run_jnb 
after_success:
  - codecov
