language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install ipython
  - pip install nbconvert
  - pip install matplotlib
# command to run tests
script:
  - pytest run_jnb 
after_success:
  - coveralls
